services:
  github-runner:
    image: myoung34/github-runner
    restart: always
    environment:
      RUNNER_NAME: alpine-runner
      REPO_URL: https://github.com/NumairHussain/Alpine-Server
      RUNNER_TOKEN: ${RUNNER_TOKEN:-xxx}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
