name: Restart All Services
run-name: ${{ github.actor }} Restarted All Services
on:
    workflow_dispatch:

jobs:
    update_service:
        runs-on: [
            self-hosted,
            linux,
            X64,
            Alpine
        ]
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Restarting Jellyfin Services
            run: |
                echo "Restarting Jellyfin service..."

                cd jellyfin
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Jellyfin failed";
                    exit 1;
                fi

                docker compose down
                if [ $? -ne 0 ]; then
                    echo "Error: Stopping Jellyfin stack failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Jellyfin stack failed";
                    exit 1;
                fi

                exit 0;

        -   name: Restarting Olympus Service
            run: |
                echo "Restarting Olympus service..."

                cd olympus-server
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Olympus-Server failed";
                    exit 1;
                fi

                docker compose down
                if [ $? -ne 0 ]; then
                    echo "Error: Stopping Olympus Server failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Olympus Server failed";
                    exit 1;
                fi

                exit 0;

        -   name: Restarting Pi-Hole Service
            run: |
                echo "Restarting Pi-Hole service..."

                cd pi-hole
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Pi-Hole failed";
                    exit 1;
                fi

                docker compose down
                if [ $? -ne 0 ]; then
                    echo "Error: Stopping Pi-Hole failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Pi-Hole failed";
                    exit 1;
                fi

                exit 0;