name: Start One Service
run-name: ${{ github.actor }} Started One Service - ${{ github.event.inputs.service_name }}
on:
    workflow_dispatch:
        inputs:
            service_name:
                description: Choose the service to start
                required: true
                type: choice
                options:
                    - Jellyfin
                    - Olympus
                    - Pi-Hole

jobs:
    update_service:
        runs-on: [
            self-hosted,
            linux,
            X64,
            Alpine
        ]
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Starting Jellyfin Services
            env:
                OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
                OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
                DUCK_DNS_TOKEN: ${{ secrets.DUCK_DNS_TOKEN }}
            if: ${{ github.event.inputs.service_name == 'Jellyfin' }}
            run: |
                echo "Starting Jellyfin service..."

                cd jellyfin
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Jellyfin failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Jellyfin stack failed";
                    exit 1;
                fi

        -   name: Starting Olympus Service
            if: ${{ github.event.inputs.service_name == 'Olympus' }}
            run: |
                echo "Starting Olympus service..."

                cd olympus-server
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Olympus-Server failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Olympus Server failed";
                    exit 1;
                fi

        -   name: Starting Pi-Hole Service
            if: ${{ github.event.inputs.service_name == 'Pi-Hole' }}
            env:
                PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
            run: |
                echo "Starting Pi-Hole service..."

                cd pi-hole
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Pi-Hole failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Pi-Hole failed";
                    exit 1;
                fi
