name: Start All Services
run-name: ${{ github.actor }} Started All Services
on:
    workflow_dispatch:
        # inputs:
        #     secrets:
        #         OPENVPN_PASSWORD:
        #             description: 'OpenVPN Password'
        #             required: true
        #         OPENVPN_USERNAME:
        #             description: 'OpenVPN Username'
        #             required: true
        #         DUCK_DNS_TOKEN:
        #             description: 'Duck DNS Token'
        #             required: true

jobs:
    start_all_services:
        runs-on: [
            self-hosted,
            linux,
            X64,
            Alpine
        ]
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Starting Jellyfin Services
            env:
                OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
                OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
                DUCK_DNS_TOKEN: ${{ secrets.DUCK_DNS_TOKEN }}
            run: |
                echo "Starting Jellyfin service..."

                cd jellyfin
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Jellyfin failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Jellyfin stack failed";
                    exit 1;
                fi

        -   name: Starting Olympus Service
            run: |
                echo "Starting Olympus service..."

                cd olympus-server
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Olympus-Server failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Olympus Server failed";
                    exit 1;
                fi

        -   name: Starting Pi-Hole Service
            env:
                PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
            run: |
                echo "Starting Pi-Hole service..."

                cd pi-hole
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Pi-Hole failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting Pi-Hole failed";
                    exit 1;
                fi
