name: Update All Services
run-name: ${{ github.actor }} Updated All Services
on:
    workflow_dispatch:

jobs:
    update_all_services:
        runs-on: [
            self-hosted,
            linux,
            X64,
            Alpine
        ]
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Update Jellyfin Services
            env:
                OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
                OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
                DUCK_DNS_TOKEN: ${{ secrets.DUCK_DNS_TOKEN }}
            run: |
                echo "Updating Jellyfin service..."

                cd jellyfin
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Jellyfin failed";
                    exit 1;
                fi

                docker compose pull
                if [ $? -ne 0 ]; then
                    echo "Error: Pulling latest Jellyfin stack image failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting updated Jellyfin service failed";
                    exit 1;
                fi

        -   name: Update Olympus Service
            run: |
                echo "Updating Olympus service..."

                cd olympus-server
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Olympus-Server failed";
                    exit 1;
                fi

                docker compose pull
                if [ $? -ne 0 ]; then
                    echo "Error: Pulling latest minecraft-bedrock image failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting updated service olympus-server failed";
                    exit 1;
                fi

        -   name: Update Pi-Hole Service
            env:
                PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
            run: |
                echo "Updating Pi-Hole service..."

                cd pi-hole
                if [ $? -ne 0 ]; then
                    echo "Error: Changing Directory to Pi-Hole failed";
                    exit 1;
                fi

                docker compose pull
                if [ $? -ne 0 ]; then
                    echo "Error: Pulling latest Pi-Hole image failed";
                    exit 1;
                fi

                docker compose up -d
                if [ $? -ne 0 ]; then
                    echo "Error: Starting updated Pi-Hole service failed";
                    exit 1;
                fi
